/*
 * INT_EX.c
 *
 *  Created on: Jul 1, 2022
 *      Author: Wels
 */
#include "INT_EX.h"

void INT_Init(void)
{
	RCC->APB2ENR |= RCC_APB2ENR_SYSCFGEN;

	SYSCFG->EXTICR[3] &= ~(SYSCFG_EXTICR4_EXTI13);
	SYSCFG->EXTICR[3] |= (SYSCFG_EXTICR4_EXTI13_PC);

	SYSCFG->EXTICR[0] &= ~(SYSCFG_EXTICR1_EXTI0);
	SYSCFG->EXTICR[0] |= (SYSCFG_EXTICR1_EXTI0_PC);


	EXTI->IMR |= EXTI_IMR_IM13;
	EXTI->EMR |= EXTI_EMR_EM13;

	EXTI->IMR |= EXTI_IMR_IM0;
	EXTI->EMR |= EXTI_EMR_EM0;


	EXTI->FTSR |= EXTI_FTSR_TR13;
	EXTI->RTSR &= ~(EXTI_RTSR_TR13);

	EXTI->FTSR |= EXTI_FTSR_TR0;
	EXTI->RTSR &= ~(EXTI_RTSR_TR0);


//	NVIC_SetPriority(EXTI0_IRQn,5);
//
//	NVIC_EnableIRQ(EXTI0_IRQn);
//
//	NVIC_SetPriority(EXTI15_10_IRQn,7);
//
//	NVIC_EnableIRQ(EXTI15_10_IRQn);

}






